// Shared Debezium helpers (Epic E2 / EDAM-T011).

import type { DebeziumConfigOptions, RawSourceEvent, SnapshotPhase } from './types.js';

/** Unwrap a schema-wrapped Debezium value ({schema, payload}) to its payload. */
export function debeziumValue(ev: RawSourceEvent): any {
  const v = ev.value as any;
  if (v && typeof v === 'object' && 'payload' in v && 'schema' in v) return v.payload;
  return v;
}

export function debeziumSource(ev: RawSourceEvent): any {
  return debeziumValue(ev)?.source ?? {};
}

/** Map Debezium's `source.snapshot` flag to a snapshot phase. */
export function mapSnapshotPhase(snapshot: unknown): SnapshotPhase {
  if (snapshot === undefined || snapshot === null || snapshot === false || snapshot === 'false') {
    return 'streaming';
  }
  if (snapshot === 'last' || snapshot === 'last_in_data_collection') return 'handoff';
  return 'snapshot';
}

export function isHeartbeatEvent(ev: RawSourceEvent): boolean {
  if (typeof ev.topic === 'string' && ev.topic.toLowerCase().includes('heartbeat')) return true;
  const v = debeziumValue(ev);
  // Heartbeats carry a timestamp but no change op and no source table.
  return !!v && typeof v === 'object' && v.op === undefined && !v?.source?.table && v.ts_ms !== undefined;
}

export function isDataChangeEvent(ev: RawSourceEvent): boolean {
  if (isHeartbeatEvent(ev)) return false;
  const v = debeziumValue(ev);
  return !!v && typeof v.op === 'string' && ['c', 'u', 'd', 'r'].includes(v.op) && !!v?.source?.table;
}

export function sourceTimestampMs(ev: RawSourceEvent): number | null {
  const v = debeziumValue(ev);
  const ts = v?.source?.ts_ms ?? v?.ts_ms;
  return typeof ts === 'number' ? ts : null;
}

/**
 * Build a Debezium Server application.properties for a connector. ROW binlog +
 * FULL row image + GTID are SOURCE-DB prerequisites (enforced by my.cnf and
 * validated by the Attestation Monitor in Epic E3); Debezium consumes them.
 */
export function buildDebeziumProperties(connectorClass: string, opts: DebeziumConfigOptions): string {
  const lines = [
    '# Generated by EDAM CDC Collector (EDAM-T011).',
    '# Source credential is READ-ONLY (INV-1). ROW + FULL row image + GTID are',
    '# source-DB prerequisites, validated by the Attestation Monitor (Epic E3).',
    'debezium.sink.type=redis',
    `debezium.sink.redis.address=${opts.redisAddress}`,
    `debezium.source.connector.class=${connectorClass}`,
    `debezium.source.topic.prefix=${opts.topicPrefix}`,
    `debezium.source.database.hostname=${opts.host}`,
    `debezium.source.database.port=${opts.port}`,
    `debezium.source.database.user=${opts.user}`,
    `debezium.source.database.password=${opts.password}`,
    `debezium.source.database.server.id=${opts.serverId}`,
    `debezium.source.database.include.list=${opts.databaseIncludeList}`,
    `debezium.source.table.include.list=${opts.tableIncludeList}`,
    'debezium.source.snapshot.mode=initial',
    `debezium.source.offset.storage.file.filename=${opts.offsetFile}`,
    'debezium.source.offset.flush.interval.ms=1000',
    'debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory',
    `debezium.source.schema.history.internal.file.filename=${opts.schemaHistoryFile}`,
    'debezium.source.binary.handling.mode=base64',
    'debezium.format.value=json',
    'debezium.format.value.schemas.enable=false',
    'debezium.format.key=json',
    'debezium.format.key.schemas.enable=false',
  ];
  if (opts.heartbeatMs) lines.push(`debezium.source.heartbeat.interval.ms=${opts.heartbeatMs}`);
  return lines.join('\n') + '\n';
}
